**Importacion de librerias.**

Importamos las librerias que se utilizaran para el analisis.

In [20]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Cargamos el archivo asociacion.csv de la clase F

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/AsaelP25/Parcial4_Humberto_Parada_2510772022/refs/heads/main/Archivos/clave_F_asociacion.csv")

In [4]:
df.head()

  transaccion_id cliente_id       fecha categoria      item  cantidad   canal
0        F-T0001    F-C0058  2026-01-02      Ropa  Camiseta         4  Tienda
1        F-T0001    F-C0058  2026-01-02  Ciclismo     Casco         1  Tienda
2        F-T0001    F-C0058  2026-01-02    Futbol   Chaleco         1  Tienda
3        F-T0001    F-C0058  2026-01-02  Ciclismo     Luces         1  Tienda
4        F-T0002    F-C0005  2026-01-09  Ciclismo     Casco         1     App

El archivo de asociación contiene registros de ventas por transacción. Incluye información como el identificador de la transacción, cliente, fecha, categoría, producto, cantidad y canal de venta.

In [5]:
df.shape

(605, 7)

# Verificar valores nulos, duplicados y tipos de datos.

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605 entries, 0 to 604
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaccion_id  605 non-null    object
 1   cliente_id      605 non-null    object
 2   fecha           605 non-null    object
 3   categoria       605 non-null    object
 4   item            605 non-null    object
 5   cantidad        605 non-null    int64
 6   canal           605 non-null    object
dtypes: int64(1), object(6)
memory usage: 33.2+ KB

El Dataset cuanto con 6 valores de typo Object y 1 valor de tipon integer

In [8]:
df.isnull().sum()

transaccion_id    0
cliente_id        0
fecha             0
categoria         0
item              0
cantidad          0
canal             1
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(1)

In [23]:
# Rellenar valores nulos en la columna canal
df["canal"] = df["canal"].fillna("No especificado")

# Eliminar registros duplicados
df = df.drop_duplicates()

Valores nulos y duplicados despues de la limpieza

In [24]:
df.isnull().sum()

transaccion_id    0
cliente_id        0
fecha             0
categoria         0
item              0
cantidad          0
canal             0
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(0)

Se revisaron los valores nulos, registros duplicados y tipos de datos. Durante la revisión inicial del dataset de asociación se identificó un valor nulo en la columna canal y un registro duplicado por lo cual se hizo una limpieza.

Instalar la librería necesaria e importarlar

In [17]:
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.12/dist-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.0.2)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.2->mlxtend) (2026.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)

In [21]:
from mlxtend.frequent_patterns import apriori, association_rules

Verificar columnas del dataset

In [26]:
df.head()

  transaccion_id cliente_id       fecha categoria      item  cantidad   canal
0        F-T0001    F-C0058  2026-01-02      Ropa  Camiseta         4  Tienda
1        F-T0001    F-C0058  2026-01-02  Ciclismo     Casco         1  Tienda
2        F-T0001    F-C0058  2026-01-02    Futbol   Chaleco         1  Tienda
3        F-T0001    F-C0058  2026-01-02  Ciclismo     Luces         1  Tienda
4        F-T0002    F-C0005  2026-01-09  Ciclismo     Casco         1     App

In [27]:
df.columns

Index(['transaccion_id', 'cliente_id', 'fecha', 'categoria', 'item',
       'cantidad', 'canal'],
      dtype='object')

Preparar los datos para Apriori

In [28]:
tabla_transacciones = df.groupby(["transaccion_id", "item"])["cantidad"].sum().unstack().fillna(0)

tabla_transacciones.head()

item,Balon,Banda_elastica,Barra_energia,Bebida_isotonica,Calcetas,Camiseta,Candado,Casco,Chaleco,Conos,Creatina,Guantes,Guantes_bici,Luces,Mancuernas,Mat,Proteina,Short,Tenis,Termo
transaccion_id,,,,,,,,,,,,,,,,,,,,
F-T0001,0.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
F-T0002,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
F-T0003,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
F-T0004,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0
F-T0005,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0

Convertir cantidades a 0 y 1

In [29]:
tabla_transacciones = tabla_transacciones.applymap(lambda x: 1 if x > 0 else 0)

tabla_transacciones.head()

/tmp/ipykernel_24967/805712911.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  tabla_transacciones = tabla_transacciones.applymap(lambda x: 1 if x > 0 else 0)

item,Balon,Banda_elastica,Barra_energia,Bebida_isotonica,Calcetas,Camiseta,Candado,Casco,Chaleco,Conos,Creatina,Guantes,Guantes_bici,Luces,Mancuernas,Mat,Proteina,Short,Tenis,Termo
transaccion_id,,,,,,,,,,,,,,,,,,,,
F-T0001,0,0,0,0,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0
F-T0002,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0
F-T0003,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
F-T0004,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0
F-T0005,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1

Se transformaron los datos para que cada fila representara una transacción y cada columna representara un producto.

Los valores se convirtieron a 1 y 0, donde 1 significa que el producto fue comprado en esa transacción y 0 significa que no fue comprado. Esta estructura es necesaria para aplicar el algoritmo Apriori.

Aplicar algoritmo Apriori

In [30]:
itemsets_frecuentes = apriori(
    tabla_transacciones,
    min_support=0.03,
    use_colnames=True
)

itemsets_frecuentes.head()

    support            itemsets
0  0.226316             (Balon)
1  0.252632    (Banda_elastica)
2  0.105263     (Barra_energia)
3  0.152632  (Bebida_isotonica)
4  0.252632          (Calcetas)

Ordenar los itemsets frecuentes

In [31]:
itemsets_frecuentes = itemsets_frecuentes.sort_values(by="support", ascending=False)

itemsets_frecuentes.head(10)

     support            itemsets
18  0.268421             (Tenis)
13  0.257895             (Luces)
1   0.252632    (Banda_elastica)
4   0.252632          (Calcetas)
0   0.226316             (Balon)
7   0.226316             (Casco)
15  0.215789               (Mat)
9   0.210526             (Conos)
3   0.152632  (Bebida_isotonica)
47  0.152632   (Calcetas, Tenis)

El soporte indica qué tan frecuente aparece un producto o combinación de productos dentro de todas las transacciones. Mientras más alto sea el soporte, más común es esa compra dentro del dataset.

Generar reglas de asociación

In [32]:
reglas = association_rules(
    itemsets_frecuentes,
    metric="confidence",
    min_threshold=0.2
)

reglas.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Calcetas),(Tenis),0.252632,0.268421,0.152632,0.604167,2.250817,1.0,0.084820,1.848199,0.743565,0.414286,0.458933,0.586397
1,(Tenis),(Calcetas),0.268421,0.252632,0.152632,0.568627,2.250817,1.0,0.084820,1.732536,0.759613,0.414286,0.422811,0.586397
2,(Banda_elastica),(Mat),0.252632,0.215789,0.136842,0.541667,2.510163,1.0,0.082327,1.711005,0.804984,0.412698,0.415548,0.587907
3,(Mat),(Banda_elastica),0.215789,0.252632,0.136842,0.634146,2.510163,1.0,0.082327,2.042807,0.767166,0.412698,0.510477,0.587907
4,(Casco),(Luces),0.226316,0.257895,0.121053,0.534884,2.074039,1.0,0.062687,1.595526,0.669329,0.333333,0.373248,0.502136

Seleccionar columnas importantes

In [33]:
reglas_importantes = reglas[
    ["antecedents", "consequents", "support", "confidence", "lift"]
]

reglas_importantes.head(10)

        antecedents       consequents   support  confidence      lift
0        (Calcetas)           (Tenis)  0.152632    0.604167  2.250817
1           (Tenis)        (Calcetas)  0.152632    0.568627  2.250817
2  (Banda_elastica)             (Mat)  0.136842    0.541667  2.510163
3             (Mat)  (Banda_elastica)  0.136842    0.634146  2.510163
4           (Casco)           (Luces)  0.121053    0.534884  2.074039
5           (Luces)           (Casco)  0.121053    0.469388  2.074039
6           (Conos)           (Balon)  0.115789    0.550000  2.430233
7           (Balon)           (Conos)  0.115789    0.511628  2.430233
8        (Calcetas)    (Guantes_bici)  0.057895    0.229167  1.674679
9    (Guantes_bici)        (Calcetas)  0.057895    0.423077  1.674679

Ordenar las mejores reglas

In [34]:
reglas_importantes = reglas_importantes.sort_values(by="lift", ascending=False)

reglas_importantes.head(10)

              antecedents       consequents   support  confidence      lift
47         (Balon, Tenis)        (Calcetas)  0.031579    0.750000  2.968750
51  (Tenis, Guantes_bici)        (Calcetas)  0.031579    0.750000  2.968750
55         (Tenis, Luces)        (Calcetas)  0.031579    0.666667  2.638889
3                   (Mat)  (Banda_elastica)  0.136842    0.634146  2.510163
2        (Banda_elastica)             (Mat)  0.136842    0.541667  2.510163
48      (Calcetas, Balon)           (Tenis)  0.031579    0.666667  2.483660
7                 (Balon)           (Conos)  0.115789    0.511628  2.430233
6                 (Conos)           (Balon)  0.115789    0.550000  2.430233
0              (Calcetas)           (Tenis)  0.152632    0.604167  2.250817
1                 (Tenis)        (Calcetas)  0.152632    0.568627  2.250817

Mostrar las 10 reglas más relevantes

In [35]:
top_10_reglas = reglas_importantes.head(10)

top_10_reglas

              antecedents       consequents   support  confidence      lift
47         (Balon, Tenis)        (Calcetas)  0.031579    0.750000  2.968750
51  (Tenis, Guantes_bici)        (Calcetas)  0.031579    0.750000  2.968750
55         (Tenis, Luces)        (Calcetas)  0.031579    0.666667  2.638889
3                   (Mat)  (Banda_elastica)  0.136842    0.634146  2.510163
2        (Banda_elastica)             (Mat)  0.136842    0.541667  2.510163
48      (Calcetas, Balon)           (Tenis)  0.031579    0.666667  2.483660
7                 (Balon)           (Conos)  0.115789    0.511628  2.430233
6                 (Conos)           (Balon)  0.115789    0.550000  2.430233
0              (Calcetas)           (Tenis)  0.152632    0.604167  2.250817
1                 (Tenis)        (Calcetas)  0.152632    0.568627  2.250817

Interpretar reglas automáticamente

In [36]:
for index, row in top_10_reglas.iterrows():
    antecedente = list(row["antecedents"])
    consecuente = list(row["consequents"])
    soporte = row["support"]
    confianza = row["confidence"]
    lift = row["lift"]

    print(f"Regla: Si compra {antecedente}, también compra {consecuente}")
    print(f"Soporte: {soporte:.2f}")
    print(f"Confianza: {confianza:.2f}")
    print(f"Lift: {lift:.2f}")
    print("-" * 60)

Regla: Si compra ['Balon', 'Tenis'], también compra ['Calcetas']
Soporte: 0.03
Confianza: 0.75
Lift: 2.97
------------------------------------------------------------
Regla: Si compra ['Tenis', 'Guantes_bici'], también compra ['Calcetas']
Soporte: 0.03
Confianza: 0.75
Lift: 2.97
------------------------------------------------------------
Regla: Si compra ['Tenis', 'Luces'], también compra ['Calcetas']
Soporte: 0.03
Confianza: 0.67
Lift: 2.64
------------------------------------------------------------
Regla: Si compra ['Mat'], también compra ['Banda_elastica']
Soporte: 0.14
Confianza: 0.63
Lift: 2.51
------------------------------------------------------------
Regla: Si compra ['Banda_elastica'], también compra ['Mat']
Soporte: 0.14
Confianza: 0.54
Lift: 2.51
------------------------------------------------------------
Regla: Si compra ['Calcetas', 'Balon'], también compra ['Tenis']
Soporte: 0.03
Confianza: 0.67
Lift: 2.48
------------------------------------------------------------
Regla: Si compra ['Balon'], también compra ['Conos']
Soporte: 0.12
Confianza: 0.51
Lift: 2.43
------------------------------------------------------------
Regla: Si compra ['Conos'], también compra ['Balon']
Soporte: 0.12
Confianza: 0.55
Lift: 2.43
------------------------------------------------------------
Regla: Si compra ['Calcetas'], también compra ['Tenis']
Soporte: 0.15
Confianza: 0.60
Lift: 2.25
------------------------------------------------------------
Regla: Si compra ['Tenis'], también compra ['Calcetas']
Soporte: 0.15
Confianza: 0.57
Lift: 2.25
------------------------------------------------------------